# Generated by Django 4.1.7 on 2023-03-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=50)),
                ('content', models.TextField(help_text='내용')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(help_text='이메일 주소', max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=50)),
                ('user', models.OneToOneField(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, to='book.user')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('post', models.ForeignKey(help_text='포스트', on_delete=django.db.models.deletion.CASCADE, to='book.post')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, to='book.user')),
            ],
            options={
                'db_table': 'post_like',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text='좋아요', related_name='r_post_likes', through='book.PostLike', to='book.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, to='book.user'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(help_text='도서들', to='book.book')),
                ('user', models.OneToOneField(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, to='book.user')),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
